# Site settings
title: Hello There
description: A little path about my dev life
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jessica Grosskopf
user_description: Bicycle to up and down, trekking - Lust for life - typewriter when I remember to left my feeling in to the Wild and in the wind.
user_title: Data Analyst
email: jgrossp@gmail.com
twitter_username: twitter.com/jgrossp
github_username:  github.com/jgrossp
gplus_username:  jgrossp

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
